#!/usr/bin/env bash
#
# Run unit tests
#
# TESTFLAGS - add additional test flags. Ex:
#
#   TESTFLAGS="-v -run TestBuild" hack/test/unit
#
# TESTDIRS - run tests for specified packages. Ex:
#
#    TESTDIRS="./pkg/term" hack/test/unit
#
set -eu -o pipefail

TESTFLAGS+=" -test.timeout=${TIMEOUT:-5m}"
BUILDFLAGS=( -tags "netgo seccomp libdm_no_deferred_remove" )
TESTDIRS="${TESTDIRS:-"./..."}"

TESTDIR_EXCLUDE=( /builder/dockerfile /builder/fscache /builder/remotecontext /daemon/graphdriver/quota /pkg/archive /pkg/chrootarchive /pkg/mount /pkg/system /plugin /volume/local )

exclude_paths="/vendor/|/integration"
if [ -n "${TESTNOPRIV:-}" ]; then
  for p in ${TESTDIR_EXCLUDE[@]}; do
    exclude_paths="$exclude_paths|$p"
  done
fi

pkg_list=$(go list $TESTDIRS | grep -vE "($exclude_paths)")

go test -cover "${BUILDFLAGS[@]}" $TESTFLAGS $pkg_list
